project:
  type: website

website:
  title: "Martin Roberts"
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - text: "<img src='martin-chappie.jpg' style='border-radius: 50%; width: 60px; height: 60px; object-fit: cover; display: block; margin: 0;' alt='Martin Roberts'>"
      - text: "<br>"
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Papers"
        href: papers.qmd
      - text: "Courses"
        href: courses.qmd     
      - text: "Blogs"
        href: blogs.qmd
      - section: "Writing"
        contents:
          - text: "Books"
            href: books.qmd
          - text: "Chapters"
            href: book-chapters.qmd
          - text: "Articles"
            href: articles.qmd
          - text: "Other"
            href: other-articles.qmd
      - section: "Conferences"
        contents:
          - text: "Invited lectures"
            href: invited.qmd
          - text: "Conferences"
            href: conferences.qmd
format:
  html:
    bread-crumbs: false
    theme: squarespace.scss
    css: styles.css
    toc: false
    grid:
      sidebar-width: 225px
      body-width: 1000px
      margin-width: 225px
      gutter-width: 2em
execute:
  freeze: true
editor: source


