project:
  type: website

website:
  title: "Martin Roberts"
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - text: "<img src='martin-chappie.jpg' style='border-radius: 50%; width: 60px; height: 60px; object-fit: cover; display: block; margin: 0;' alt='Martin Roberts'>"
      - text: "<br>"

      - section: "Projects"
        contents:
          - text: "Twilighting"
            href: twilighting.qmd
          - text: "Endless Summer"
            href: endless-summer.qmd
          - text: "Entangled Lives"
            href: entangled-lives.qmd
          - text: "Three-Dimensional Music"
            href: 3d-music.qmd
          - text: "Moving Targets"
            href: moving-targets.qmd
          - text: "Dangerous Liaisons"
            href: dangerous-liaisons.qmd
          - text: "Double Happiness"
            href: double-happiness.qmd
          - text: "Torrential Noise"
            href: torrential-noise.qmd
          - text: "Imagine"
            href: imagine.qmd
      - text: "Papers"
        href: papers.qmd
      - text: "Courses"
        href: courses.qmd     
      - text: "Blogs"
        href: blogs.qmd
      - section: "Writing"
        contents:
          - text: "Books"
            href: books.qmd
          - text: "Chapters"
            href: book-chapters.qmd
          - text: "Articles"
            href: articles.qmd
          - text: "Other"
            href: other-articles.qmd
      - section: "Conferences"
        contents:
          - text: "Invited lectures"
            href: invited.qmd
          - text: "Conferences"
            href: conferences.qmd
      - text: "Bio"
        href: bio.qmd
      - text: "Contact"
        href: contact.qmd
format:
  html:
    bread-crumbs: false
    theme: squarespace.scss
    css: styles.css
    toc: false
    grid:
      sidebar-width: 225px
      body-width: 1200px
      margin-width: 225px
      gutter-width: 2em
execute:
  freeze: true
editor: source


