project:
  type: website

website:
  title: "Martin Roberts"
  sidebar:
    style: "floating"
    search: false
    collapse-level: 1
    contents:
      - text: "<img src='martin-chappie.jpg' style='border-radius: 50%; width: 60px; height: 60px; object-fit: cover; display: block; margin: 0;' alt='Martin Roberts'>"
      - text: "<br>"
      - text: "About"
        href: about.qmd
      - text: "Contact"
        href: contact.qmd
      - text: "Recent Papers"
        href: recent-papers.qmd
      - section: "Course Websites"
        contents: 
          - text: "Emerson College"
            href: emerson.qmd     
      - text: "Blogs"
        href: blogs.qmd
      - section: "Writing"
        contents:
          - text: "Books"
            href: books.qmd
          - text: "Articles"
            href: articles.qmd
          - text: "Other"
            href: other-writing.qmd
      - section: "Conferences"
        contents:
          - text: "Invited lectures"
            href: invited.qmd
          - text: "Conferences"
            href: conferences.qmd
format:
  html:
    #bread-crumbs: false
    theme: squarespace.scss
    toc: false
    grid:
      sidebar-width: 225px
      body-width: 1000px
      margin-width: 225px
      gutter-width: 2em



