---
title: "    "
---

## Book Chapters

“Baraka: World Cinema and the Global Culture Industry.” In Denilson Lopes and Andrea França, eds., Cinema, Globalizacão e Interculturalidade (Cinema,Globalization,and Interculturality) (Chapecó, Brazil: Argos Editora Universitária, 2010).

“The Fashion Police: Governing the Self in What Not To Wear.” In Diane Negra and Yvonne Tasker, eds., Interrogating Postfeminism: Gender and the Politics of Popular Culture (Duke University Press, 2007).

“Notes on the Global Underground: Subcultures and Globalization.” In Ken Gelder, ed., The Subcultures Reader, second edition (New York: Routledge, 2005).

“Film Culture.” In Adam Muller, ed., Concepts of Culture: Art, Politics, and Society (Calgary: University of Calgary Press, 2005).

“Decoding D-Day: Multi-Channel Television at the Millennium.” In Mette Hjort and Scott Mackenzie, eds., Purity and Provocation: Dogma ’95 (London: BFI, 2003).

“Indonesia: The Movie.” In Mette Hjort and Scott MacKenzie, eds., Cinema and Nation (New York: Routledge, 2000).

“Transnational Geographic: Perspectives on Baraka.” In Isabel Santaolalla, ed., New Exoticisms: Changing Patterns in the Construction of Otherness (Amsterdam and Atlanta, GA: Rodopi, 2000).

“World Music: The Relocation of Culture.” World Culture Report 1998: Culture, Creativity and Markets (Paris: UNESCO, 1998).
