---
title: "    "
---

[Democracy in Cyberspace: Society, Politics, and the Virtual Republic](https://dokoissho.sdf.org/mit/commforum/)\

5 May 1994\
Room E40-242A\
MIT Media Lab\
Cambridge, MA 02139\

Julian Dibbell\
The Village Voice

Amy Bruckman\
The Media Lab\
Massachusetts Institute of Technology

F. Randall Farmer\
Electric Communities

Dr. Martin Roberts, Moderator\
Foreign Languages & Literatures / Film & Media Studies\
Massachusetts Institute of Technology

**Note**\
This forum is no longer avilable online on the official MIT Communications Forum archive, whose earliest entry only goes back as far as 7 December 1995. It was available at one time as what appears to have been an OCR-scanned PDF of a typed transcript of an audio recording of the event that was made at the time, but this has since been taken down and my downloaded copy of the PDF has disappeared into my own archive of ancient external drives.

The page linked to above is thus an edited version of a PDF-to-text conversion of an OCR-scanned PDF of a transcript of an audio recording. In this process of repeated copying, noise was inevitably introduced, as the quality of the video signal of a VCR tape degrades across multiple generations of copies. The original audio transcript itself is unreliable, with occasional transcription errors, typos, and missing words. I have done my best to correct these, inferring meanings and inserting what appear to be missing words where necessary. All such edits are indicated in square brackets [thus], but this was not an exact science (an appropriate metaphor in the context), and in a few places there are some glitches in the data flow where the original words of the speakers were unclear. These places are flagged by [???] in the contemporary version.

Since the Communications Forum has continued into the present, maybe it’s time for a forum on glitch media archaeology and the erratic interplay between analog and digital as data flows across unstable platforms.

---Martin Roberts, Seoul, 22 June 2023

***

